//! Reference research module: 9-stage employee lifecycle ABM.
//!
//! Implements the HR lifecycle model from the design document §9, covering:
//!
//! 1. `hiring` — selection validity, new-hire onboarding
//! 2. `socialization` — onboarding quality mediates retention
//! 3. `learning_curve` — productivity ramp `θ(1 − e^{−λ·tenure})`
//! 4. `peer_effect` — effective productivity scaled by team mean θ
//! 5. `ocb` — organisational citizenship behaviour adds to team knowledge
//! 6. `fit` — P-O/P-J fit drives satisfaction and turnover intent
//! 7. `turnover` — network-contagion quit process (Krackhardt cascade)
//! 8. `knowledge_loss` — tacit knowledge drain on departure
//! 9. `toxic_spread` — toxic worker infection along network edges
//! 10. `org_performance` — aggregate metrics (Reward phase)
//!
//! # Calibration
//!
//! All default parameter values are collected as `pub const` in the
//! [`calibration`] module together with the original source citations.
//!
//! # Usage
//!
//! ```rust,no_run
//! use socsim_packs::hr_lifecycle::{HrWorld, HrLifecyclePack};
//! use socsim_config::{Registry, ModulePack, Params};
//!
//! let mut rng = socsim_core::SimRng::from_seed(42);
//! let world = HrWorld::new(5, 8, 4, 0.1, &mut rng);
//!
//! let mut reg = Registry::new();
//! HrLifecyclePack.register(&mut reg);
//!
//! let p = Params::empty();
//! let mechanisms: Vec<_> = [
//!     "learning_curve", "peer_effect", "ocb", "fit",
//!     "turnover", "knowledge_loss", "toxic_spread",
//!     "hiring", "socialization", "org_performance",
//! ]
//! .iter()
//! .map(|name| reg.build(name, &p).unwrap())
//! .collect();
//! ```

pub mod calibration;
#[cfg(feature = "marl")]
pub mod marl;
mod mechanisms;
mod world;

pub use mechanisms::HrLifecyclePack;
pub use world::{Employee, HrWorld, Team};

/// Starter scenario TOML for the `hr-lifecycle` pack, emitted by
/// `socsim init --module-pack hr-lifecycle`.
pub const HR_LIFECYCLE_STARTER: &str = r#"# HR Lifecycle Scenario — generated by `socsim init`
# Edit parameters as needed, then run with:
#   socsim run <this-file>

[simulation]
name        = "hr_lifecycle_baseline"
module_pack = "hr-lifecycle"
t_max       = 60
seed        = 42
scheduler   = "random_activation"

[world]
n_teams           = 5
team_size_initial = 8
network_model     = "watts_strogatz"
network_k         = 4
network_beta      = 0.1

[[mechanism]]
name  = "learning_curve"
phase = "environment"
[mechanism.params]
lambda_learn = 0.15

[[mechanism]]
name  = "peer_effect"
phase = "interaction"
[mechanism.params]
alpha_peer = 0.17

[[mechanism]]
name  = "ocb"
phase = "interaction"
[mechanism.params]
alpha_k = 0.30

[[mechanism]]
name  = "fit"
phase = "decision"
[mechanism.params]
rho_pj = 0.20
rho_po = 0.07

[[mechanism]]
name  = "turnover"
phase = "decision"
[mechanism.params]
rho_po_turn       = -0.35
base_quit_logit   = -4.82
quit_embed_sens   = 1.0
quit_sat_sens     = 0.8
quit_cascade_bump = 0.30

[[mechanism]]
name  = "knowledge_loss"
phase = "post_step"
[mechanism.params]
phi_tacit  = 0.85
beta_loss  = 1.0
kappa_loss = 0.40

[[mechanism]]
name  = "toxic_spread"
phase = "interaction"
[mechanism.params]
p_toxic  = 0.04
p_spread = 0.46

[[mechanism]]
name  = "hiring"
phase = "decision"
[mechanism.params]
rho_si  = 0.51
p_toxic = 0.04

[[mechanism]]
name  = "socialization"
phase = "post_step"

[[mechanism]]
name  = "org_performance"
phase = "reward"

[output]
log_path = "runs/{name}_{seed}.jsonl"
metrics  = ["org_performance", "avg_tenure", "turnover_rate", "knowledge_stock"]
"#;
