//! Module-pack dispatch table.
//!
//! Add new packs here by:
//! 1. Implementing a world factory closure.
//! 2. Implementing a register closure.
//! 3. Adding a `"pack-name"` arm to [`dispatch`] and the starter TOML to
//!    [`starter_toml`].
//! 4. Adding the name to [`known_packs`].

use anyhow::{bail, Result};

use socsim_config::{ModulePack, Params, Registry};
use socsim_core::SimRng;
use socsim_hr_lifecycle::{HrLifecyclePack, HrWorld};
use socsim_runner::WorldFactory;

// ── Dispatch ──────────────────────────────────────────────────────────────────

/// Boxed register closure (erased concrete pack type).
pub type RegisterFn<W> = Box<dyn Fn(&mut Registry<W>) + Send + Sync>;

/// Return the world factory and register function for the named pack.
///
/// # Errors
///
/// Returns `Err` when `pack_name` is not recognised.
pub fn dispatch(pack_name: &str) -> Result<(WorldFactory<HrWorld>, RegisterFn<HrWorld>)> {
    match pack_name {
        "hr-lifecycle" => {
            let factory: WorldFactory<HrWorld> = Box::new(|params: &Params, seed: u64| {
                let n_teams = params.get_u64("n_teams", 5) as usize;
                let team_size = params.get_u64("team_size_initial", 8) as usize;
                let ws_k = params.get_u64("network_k", 4) as usize;
                let ws_beta = params.get_f64("network_beta", 0.1);
                let mut rng = SimRng::from_seed(seed);
                let world = HrWorld::new(n_teams, team_size, ws_k, ws_beta, &mut rng);
                Ok(world)
            });

            let register: RegisterFn<HrWorld> = Box::new(|reg| {
                HrLifecyclePack.register(reg);
            });

            Ok((factory, register))
        }
        other => bail!(
            "unknown module pack '{other}'; known packs: {}",
            known_packs().join(", ")
        ),
    }
}

/// Return the sorted names of mechanisms registered by `register`.
pub fn mechanism_names(_pack_name: &str, register: &dyn Fn(&mut Registry<HrWorld>)) -> Vec<String> {
    let mut reg: Registry<HrWorld> = Registry::new();
    register(&mut reg);
    let mut names: Vec<String> = reg.names().into_iter().map(|s| s.to_owned()).collect();
    names.sort();
    names
}

/// Return the names of all known module packs.
pub fn known_packs() -> &'static [&'static str] {
    &["hr-lifecycle"]
}

// ── Starter TOMLs ─────────────────────────────────────────────────────────────

/// Return a starter scenario TOML string for the named pack, or an error if
/// the pack is unknown.
pub fn starter_toml(pack_name: &str) -> Result<&'static str> {
    match pack_name {
        "hr-lifecycle" => Ok(HR_LIFECYCLE_STARTER),
        other => bail!(
            "unknown module pack '{other}'; known packs: {}",
            known_packs().join(", ")
        ),
    }
}

const HR_LIFECYCLE_STARTER: &str = r#"# HR Lifecycle Scenario — generated by `socsim init`
# Edit parameters as needed, then run with:
#   socsim run <this-file>

[simulation]
name        = "hr_lifecycle_baseline"
module_pack = "hr-lifecycle"
t_max       = 60
seed        = 42
scheduler   = "random_activation"

[world]
n_teams           = 5
team_size_initial = 8
network_model     = "watts_strogatz"
network_k         = 4
network_beta      = 0.1

[[mechanism]]
name  = "learning_curve"
phase = "environment"
[mechanism.params]
lambda_learn = 0.15

[[mechanism]]
name  = "peer_effect"
phase = "interaction"
[mechanism.params]
alpha_peer = 0.17

[[mechanism]]
name  = "ocb"
phase = "interaction"
[mechanism.params]
alpha_k = 0.30

[[mechanism]]
name  = "fit"
phase = "decision"
[mechanism.params]
rho_pj = 0.20
rho_po = 0.07

[[mechanism]]
name  = "turnover"
phase = "decision"
[mechanism.params]
rho_po_turn       = -0.35
base_quit_logit   = -4.82
quit_embed_sens   = 1.0
quit_sat_sens     = 0.8
quit_cascade_bump = 0.30

[[mechanism]]
name  = "knowledge_loss"
phase = "post_step"
[mechanism.params]
phi_tacit  = 0.85
beta_loss  = 1.0
kappa_loss = 0.40

[[mechanism]]
name  = "toxic_spread"
phase = "interaction"
[mechanism.params]
p_toxic  = 0.04
p_spread = 0.46

[[mechanism]]
name  = "hiring"
phase = "decision"
[mechanism.params]
rho_si  = 0.51
p_toxic = 0.04

[[mechanism]]
name  = "socialization"
phase = "post_step"

[[mechanism]]
name  = "org_performance"
phase = "reward"

[output]
log_path = "runs/{name}_{seed}.jsonl"
metrics  = ["org_performance", "avg_tenure", "turnover_rate", "knowledge_stock"]
"#;
